"""Dataset roles and profiles (Phase 3).

One `DatasetProfile` per dataset FRAME knows about, holding what is DOCUMENTED about it:
its role, whether its pairs are synthetic or real, which splits it may appear in, its
bands, resolutions and scale factors, and its licence. QC checks every manifest record
against its profile, so a rule like "SEN2NEON is never training data" is enforced, not
merely written down.

Sources
-------
* Roles and tiers: docs/Requirements 142.txt, Requirement 3 sections 24-28 and 35-36
  (lines 3181-3526) and the dataset hierarchy at lines 3873-3906 and 11477-11501:

      TRAIN        SEN2NAIPv2 (synthetic, primary)   + SEN2VENuS (supplementary)
      VALIDATION   SEN2NAIPv2 cross-sensor
      FINAL TEST   SEN2NEON (12-band, 2.5 m)  +  OpenSR-Test  +  Indian holdout

* Per-dataset facts (bands, sizes, scales, licences) were checked against the datasets'
  own published cards during Phase 3, not only the requirements document:
    - SEN2NAIPv2  huggingface.co/datasets/tacofoundation/SEN2NAIPv2  (card, 2025-02-01)
    - SEN2NEON    huggingface.co/datasets/isp-uv-es/SEN2NEON          (card + metadata.csv)
    - SEN2VENuS   zenodo.org/records/14603764                          (record description)
    - OpenSR-Test the existing adapter, frame/validation/opensr_test_adapter.py

Where the requirements and a dataset card differ (patch sizes: the requirements speak of
128 / 512 model tiles, SEN2NAIPv2 ships 130 / 520 pixel patches), the profile records the
dataset's own facts and the patch extractor bridges the two.

`status` says honestly how far each dataset is implemented in FRAME right now.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, FrozenSet, Mapping, Optional, Tuple

from frame.data.bands import L2A_BANDS
from frame.data.contract import DatasetRole, PairType, Split
from frame.data.errors import ContractError
from frame.preprocessing import RGBN_BANDS

_TRAIN_VAL = frozenset({Split.TRAIN, Split.VAL})
_VAL = frozenset({Split.VAL})
_TEST = frozenset({Split.TEST})

STATUS_REAL = "implemented: real data read and tested"
STATUS_FIXTURE = "implemented against the documented format; tested on synthetic fixtures only, no real data read"
STATUS_PLANNED = "planned: profile only, no data and no reader"
STATUS_SYNTHETIC = "generated by FRAME: synthetic scenes for smoke tests, no real imagery"


@dataclass(frozen=True)
class VariantSpec:
    """One coherent way a dataset is used: bands, scale, sizes, role."""

    name: str
    role: DatasetRole
    pair_type: PairType
    allowed_splits: FrozenSet[Split]
    lr_bands: Tuple[str, ...]
    hr_bands: Tuple[str, ...]
    scale_factor: int
    lr_pixel_size_m: Optional[float]
    hr_pixel_size_m: Optional[float]
    lr_size: Optional[Tuple[int, int]] = None      # (height, width) of one source tile
    hr_size: Optional[Tuple[int, int]] = None
    reflectance_scale: Optional[float] = 10_000.0
    notes: str = ""


@dataclass(frozen=True)
class DatasetProfile:
    dataset: str
    title: str
    variants: Mapping[str, VariantSpec]
    scene_unit: str                 # what a scene_id means here: the unit that must never span two splits
    region_unit: Optional[str]      # what a region_id means here
    license: str
    status: str
    source: str
    requirements_ref: str
    caveats: Tuple[str, ...] = ()

    def variant(self, name: str) -> VariantSpec:
        try:
            return self.variants[name]
        except KeyError:
            raise ContractError(
                f"{self.dataset} has no variant {name!r}; known: {sorted(self.variants)}.", code="unknown_variant"
            ) from None


def _v(**kw) -> VariantSpec:
    return VariantSpec(**kw)


DATASET_PROFILES: Dict[str, DatasetProfile] = {
    # ------------------------------------------------------------------------------------------ SEN2NAIPv2
    "sen2naipv2": DatasetProfile(
        dataset="sen2naipv2",
        title="SEN2NAIPv2 (RGBN, NAIP 2.5 m / Sentinel-2-like 10 m)",
        variants={
            "unet": _v(
                name="unet", role=DatasetRole.TRAINING_PRIMARY, pair_type=PairType.SYNTHETIC, allowed_splits=_TRAIN_VAL,
                lr_bands=RGBN_BANDS, hr_bands=RGBN_BANDS, scale_factor=4, lr_pixel_size_m=10.0, hr_pixel_size_m=2.5,
                lr_size=(130, 130), hr_size=(520, 520),
                notes="62,242 pairs (card). LR is NAIP degraded by blur+bilinear downsampling, U-Net reflectance harmonisation, noise.",
            ),
            "histmatch": _v(
                name="histmatch", role=DatasetRole.TRAINING_PRIMARY, pair_type=PairType.SYNTHETIC, allowed_splits=_TRAIN_VAL,
                lr_bands=RGBN_BANDS, hr_bands=RGBN_BANDS, scale_factor=4, lr_pixel_size_m=10.0, hr_pixel_size_m=2.5,
                lr_size=(130, 130), hr_size=(520, 520),
                notes="61,282 samples (card). As 'unet' but reflectance harmonised by histogram matching to the closest Sentinel-2 image.",
            ),
            "crosssensor": _v(
                name="crosssensor", role=DatasetRole.VALIDATION, pair_type=PairType.REAL_CROSS_SENSOR, allowed_splits=_VAL,
                lr_bands=RGBN_BANDS, hr_bands=RGBN_BANDS, scale_factor=4, lr_pixel_size_m=10.0, hr_pixel_size_m=2.5,
                lr_size=(130, 130), hr_size=(520, 520),
                notes="8,000 samples (card): REAL Sentinel-2 within one day of NAIP, cloud cover 0 %. Development validation only.",
            ),
        },
        scene_unit="the source ROI/patch grid cell (NOT verified: the TACO metadata schema was not read in Phase 3; a manifest must supply it)",
        region_unit="a geographic block of the US NAIP coverage (must be supplied by the manifest builder)",
        license="CC0-1.0",
        status=STATUS_FIXTURE,
        source="https://huggingface.co/datasets/tacofoundation/SEN2NAIPv2 (139.1 GB in TACO format; needs `tacoreader`, not installed)",
        requirements_ref="Requirements 142.txt Req.3 sections 9-11, 24, 35 (lines 2810-2890, 3181-3196, 3456-3480)",
        caveats=(
            "Distributed as .taco files; FRAME does not read them. Records are built from an export the user makes (docs/DATA.md).",
            "The card's own 'Split Strategy' is 'stratified'; FRAME does not reuse it, it assigns splits by region.",
            "Patches are 130x130 LR / 520x520 HR; model crops are 128x128 / 512x512 (frame.data.patches).",
            "Value scale for the stored uint16 is not stated on the card; the manifest must state it (default 10000, unverified).",
        ),
    ),
    # ------------------------------------------------------------------------------------------ SEN2VENuS
    "sen2venus": DatasetProfile(
        dataset="sen2venus",
        title="SEN2VENuS (Sentinel-2 / VENuS 5 m, same-day)",
        variants={
            "rgbn_10m": _v(
                name="rgbn_10m", role=DatasetRole.TRAINING_SUPPLEMENTARY, pair_type=PairType.REAL_CROSS_SENSOR,
                allowed_splits=_TRAIN_VAL,
                lr_bands=("B02", "B03", "B04", "B08"), hr_bands=("B02", "B03", "B04", "B08"), scale_factor=2,
                lr_pixel_size_m=10.0, hr_pixel_size_m=5.0, lr_size=(128, 128), hr_size=(256, 256),
                notes="Band order is the FILE order b2b3b4b8, NOT FRAME's RGBN order; select_bands reorders explicitly.",
            ),
            "rededge_20m": _v(
                name="rededge_20m", role=DatasetRole.TRAINING_SUPPLEMENTARY, pair_type=PairType.REAL_CROSS_SENSOR,
                allowed_splits=_TRAIN_VAL,
                lr_bands=("B05", "B06", "B07", "B8A"), hr_bands=("B05", "B06", "B07", "B8A"), scale_factor=4,
                lr_pixel_size_m=20.0, hr_pixel_size_m=5.0, lr_size=(64, 64), hr_size=(256, 256),
                notes="20 m -> 5 m. B11/B12 are shipped LR-only (VENuS has no SWIR): they form no LR-HR pair.",
            ),
        },
        scene_unit="a pair id {site}_{acquisition_date}_{mgrs_tile} (one same-day S2/VENuS acquisition)",
        region_unit="the site (29 sites; one zip per site)",
        license="mixed per file: Sentinel-2 patches Etalab-2.0; VENuS patches CC-BY-NC-4.0 (NON-COMMERCIAL); other files CC-BY-4.0",
        status=STATUS_FIXTURE,
        source="https://zenodo.org/records/14603764 (139.5 GB, 29 site zips)",
        requirements_ref="Requirements 142.txt Req.3 sections 3-4, 25 (lines 2622-2690, 3199-3216)",
        caveats=(
            "Real S2 LR but a 5 m HR target and only 8 of the 12 bands: supplementary, never 'the 12-band 2.5 m task'.",
            "LR is Theia L2A, not the ESA L2A the deployed pipeline consumes (a processing-chain difference).",
            "The VENuS half is CC-BY-NC: any model trained on it inherits a non-commercial constraint to be checked.",
            "Pixel values are int16 to be divided by 10000.",
        ),
    ),
    # ------------------------------------------------------------------------------------------ SEN2NEON
    "sen2neon": DatasetProfile(
        dataset="sen2neon",
        title="SEN2NEON (12-band Sentinel-2 L2A LR / AVIRIS-NG-derived 2.5 m HR)",
        variants={
            "2.5m": _v(
                name="2.5m", role=DatasetRole.INDEPENDENT_BENCHMARK, pair_type=PairType.REAL_CROSS_SENSOR,
                allowed_splits=_TEST, lr_bands=L2A_BANDS, hr_bands=L2A_BANDS, scale_factor=4,
                lr_pixel_size_m=10.0, hr_pixel_size_m=2.5, lr_size=(256, 256), hr_size=(1024, 1024),
                notes="Canonical paper benchmark. A supplementary aligned 1 m product (x10) also exists and is not used.",
            ),
        },
        scene_unit="a NEON acquisition (neon_acquisition_id, e.g. 2018_MLBS_3): tiles of one flight are adjacent",
        region_unit="the NEON site code (e.g. MLBS); 49 sites",
        license="CC-BY-4.0",
        status=STATUS_REAL,
        source="https://huggingface.co/datasets/isp-uv-es/SEN2NEON (354.6 GB; LR+2.5 m HR = ~30 GB)",
        requirements_ref="Requirements 142.txt Req.3 sections 13-16, 26 (lines 2912-3013, 3220-3230)",
        caveats=(
            "INDEPENDENT BENCHMARK: never used for training. The card itself ships a single 'validation' split.",
            "The LR stack is a convenience product: all 12 bands sampled onto one 10 m grid; B1/B9 (60 m) and the 20 m bands "
            "were NOT measured at 10 m.",
            "The HR is derived from AVIRIS-NG hyperspectral data convolved with Sentinel-2 spectral response functions.",
            "LR nodata is 65535 and HR nodata is 0; many tiles have large NEON nodata fractions.",
            "North American NEON sites only: no evidence about Indian landscapes.",
            "A 20 Aug 2026 release correction replaced the LR files; manifests record the dataset revision.",
        ),
    ),
    # ------------------------------------------------------------------------------------------ OpenSR-Test
    "opensr_test": DatasetProfile(
        dataset="opensr_test",
        title="OpenSR-Test (real-world S2 benchmark; NAIP/SPOT/Venus/Spain)",
        variants={
            name: _v(
                name=name, role=DatasetRole.INDEPENDENT_BENCHMARK, pair_type=PairType.REAL_CROSS_SENSOR, allowed_splits=_TEST,
                lr_bands=L2A_BANDS, hr_bands=RGBN_BANDS, scale_factor=4, lr_pixel_size_m=10.0, hr_pixel_size_m=2.5,
                lr_size=(128, 128), hr_size=(512, 512),
                notes="Supported by the existing frame.validation adapter (LR 128x128, x4).",
            )
            for name in ("spot", "spain_crops", "spain_urban")
        },
        scene_unit="an ROI (the 'roi' column of the subset metadata)",
        region_unit=None,
        license="MIT (dataset repository)",
        status=STATUS_REAL,
        source="https://huggingface.co/datasets/isp-uv-es/opensr-test",
        requirements_ref="Requirements 142.txt Req.3 sections 17-19, 22, 27 (lines 3017-3086, 3133-3151, 3234-3246)",
        caveats=(
            "BENCHMARK: never used for training (the requirements' contamination warning, lines 3066-3086).",
            "The 'naip' (LR 121x121) and 'venus' (x2) subsets are not supported by the existing adapter and are not profiled.",
            "The LR is the full 12-band L2A stack; the HR is RGBNIR only.",
        ),
    ),
    # ------------------------------------------------------------------------------------------ synthetic smoke set
    "synthetic_smoke": DatasetProfile(
        dataset="synthetic_smoke",
        title="FRAME synthetic smoke dataset (generated RGBN scenes, LR from FRAME's degradation)",
        variants={
            "default": _v(
                name="default", role=DatasetRole.SMOKE_TEST, pair_type=PairType.SYNTHETIC,
                allowed_splits=frozenset({Split.TRAIN, Split.VAL, Split.TEST}), lr_bands=RGBN_BANDS, hr_bands=RGBN_BANDS,
                scale_factor=4, lr_pixel_size_m=10.0, hr_pixel_size_m=2.5, lr_size=(128, 128), hr_size=(512, 512),
                notes="Piecewise-constant 'land cover' scenes with sharp edges and lines; LR = frame_default_v1 degradation of the stored HR.",
            ),
        },
        scene_unit="one generated scene (R<region>_S<scene>)",
        region_unit="a generated region: a group of scenes that must stay in one split",
        license="CC0-1.0",
        status=STATUS_SYNTHETIC,
        source="frame.data.adapters.synthetic (deterministic from a seed)",
        requirements_ref="Degradation grounding: Requirements 142.txt Req.3 sections 6, 9, 30-31 (lines 2741-2757, 2820-2836, 3333-3350); Phase 4 smoke experiments",
        caveats=(
            "Synthetic: any metric on it is not evidence about real Sentinel-2 imagery or about any model's real-world quality.",
            "The LR comes from frame_default_v1 (parameters_verified=False), which is not the published SEN2NAIPv2 degradation.",
            "Exists to exercise the manifest -> split -> train -> validate path end to end; never a benchmark.",
        ),
    ),
    # ------------------------------------------------------------------------------------------ Indian holdout
    "india_holdout": DatasetProfile(
        dataset="india_holdout",
        title="Indian geographic holdout (Sentinel-2 L2A; HR reference where accessible)",
        variants={
            "default": _v(
                name="default", role=DatasetRole.DOMAIN_HOLDOUT, pair_type=PairType.INDEPENDENT_HR_REFERENCE,
                allowed_splits=_TEST, lr_bands=L2A_BANDS, hr_bands=RGBN_BANDS, scale_factor=4,
                lr_pixel_size_m=10.0, hr_pixel_size_m=None,
                notes="scale_factor is the SR factor FRAME applies (x4); an HR reference, if any, defines the real ratio.",
            ),
        },
        scene_unit="a Sentinel-2 acquisition over an Indian held-out location",
        region_unit="the held-out geographic region (for example a state or district)",
        license="Copernicus Sentinel data terms; any HR reference carries its own licence",
        status=STATUS_PLANNED,
        source="Bhoonidhi / Copernicus (availability of HR references still to be investigated)",
        requirements_ref="Requirements 142.txt Req.3 sections 28-29, 34 and Req.9 sections 24-27 (lines 3250-3330, 3433-3452, 11447-11553)",
        caveats=(
            "No data exists in FRAME yet and no HR label is invented: hr_status is 'unknown' until a real reference is found.",
            "Held-out LOCATIONS, diversity and consistent preprocessing are required before calling it a study "
            "('Indian-domain evaluation', not 'India-optimised model').",
        ),
    ),
}


def get_profile(dataset: str) -> DatasetProfile:
    try:
        return DATASET_PROFILES[dataset]
    except KeyError:
        raise ContractError(f"Unknown dataset {dataset!r}; known: {sorted(DATASET_PROFILES)}.", code="unknown_dataset") from None
